language: cpp

# we test these 3 operating systems
os: 
- linux
# uncomment as soon as travis has cmake >= 3.12 for osx
# - osx
- windows

env:
  # and do debug/release builds for each
  jobs:
    - CMAKE_CONFIGURATION=release BUILD_DIR=build
    - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug
  global:
    - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=ON -DOPTION_BUILD_TESTS=ON"
    - OMP_NUM_THREADS=2

# also build clang on linux, this depends on linux being the first in os list
# clang needs some help to find omp, thus the LD_LIBRARY_PATH
jobs:
    include:
        - compiler: clang
          env:
            - CMAKE_CONFIGURATION=release BUILD_DIR=build
            - LD_LIBRARY_PATH=/usr/local/clang/lib
        - compiler: clang
          env:
            - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug
            - LD_LIBRARY_PATH=/usr/local/clang/lib

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PATH:/c/Program Files/CMake/bin"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"; fi
  - chmod +x ./configure
  - ./configure
  - ./configure $CMAKE_CONFIGURATION

script:
  - cmake --build $BUILD_DIR
  - cmake --build $BUILD_DIR --target test
